### ISSUE TITLE
[bug] Step fails if any of the execution object is missing

### ISSUE THREAD

**Issue by scriptnull** [Shippable/kermit-execTemplates#200]
https://github.com/Shippable/pm/issues/12363

Ran a simple job 
```yml
      - name: test_basic_execute
        type: powershell
        requires:
          steps:
            - start
        execution:
          onExecute:
            - Write-Output "hi"
```

and it failed. On running the script by stopping the reqKick, noticed that the script tries to execute the sections of YML that are not generated by the YML. (in this case: onSuccess, onFailure, onComplete).

So, we need to add check for each command before calling them.
